"""empty message

Revision ID: 0be79e159823
Revises: 6101eb4a671b
Create Date: 2021-12-07 12:22:02.198747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be79e159823'
down_revision = '6101eb4a671b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.DateTime(), nullable=False),
    sa.Column('skills_id', sa.Integer(), nullable=False),
    sa.Column('sponsors_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['sponsors_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feedbacks', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('feedbacks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feedbacks', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'feedbacks', 'users', ['user_id'], ['id'])
    op.add_column('group', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('group', sa.Column('users_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'group', 'events', ['event_id'], ['id'])
    op.drop_constraint('user_address_user_id_key', 'user_address', type_='unique')
    op.drop_constraint('user_address_user_id_fkey', 'user_address', type_='foreignkey')
    op.drop_column('user_address', 'user_id')
    op.add_column('users', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'event_id')
    op.add_column('user_address', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_address_user_id_fkey', 'user_address', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('user_address_user_id_key', 'user_address', ['user_id'])
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'users_id')
    op.drop_column('group', 'event_id')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'user_id')
    op.drop_column('feedbacks', 'event_id')
    op.drop_table('events')
    # ### end Alembic commands ###
