"""sponsors_model

Revision ID: 178dfb91a8ec
Revises: b0c22941f6c3
Create Date: 2021-12-07 10:45:46.160210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178dfb91a8ec'
down_revision = 'b0c22941f6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsors')
    # ### end Alembic commands ###
