"""empty message

Revision ID: 1b177f36fd57
Revises: 4cfc6966be8c
Create Date: 2021-12-07 20:08:36.829560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b177f36fd57'
down_revision = '4cfc6966be8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.drop_constraint('avatars_img_key', 'avatars', type_='unique')
    op.drop_column('avatars', 'img')
    op.drop_column('avatars', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('avatars', sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('avatars_img_key', 'avatars', ['img'])
    op.drop_column('avatars', 'data')
    # ### end Alembic commands ###
