"""empty message

Revision ID: 22ae1cea3d9e
Revises: cfac3cafdabe
Create Date: 2021-12-08 12:34:08.914104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ae1cea3d9e'
down_revision = 'cfac3cafdabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_hash')
    # ### end Alembic commands ###
