"""empty message

Revision ID: 3ed79470eae9
Revises: 6b538a92a99c
Create Date: 2021-12-08 16:46:37.544323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed79470eae9'
down_revision = '6b538a92a99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('pending', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'pending')
    # ### end Alembic commands ###
