"""empty message

Revision ID: 57d000520ed4
Revises: bf0807f83259
Create Date: 2021-12-09 14:44:37.723835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d000520ed4'
down_revision = 'bf0807f83259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'skills_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'sponsors_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'pending',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'pending',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('events', 'sponsors_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'skills_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
