"""group_relations

Revision ID: 7312b1fc8c65
Revises: b9683b43662c
Create Date: 2021-12-14 17:53:23.759622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7312b1fc8c65'
down_revision = 'b9683b43662c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('group_users_id_fkey', 'group', type_='foreignkey')
    op.drop_column('group', 'name')
    op.drop_column('group', 'mentor_name')
    op.drop_column('group', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('group', sa.Column('mentor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('group_users_id_fkey', 'group', 'users', ['users_id'], ['id'])
    op.drop_table('event_group')
    # ### end Alembic commands ###
