"""empty message

Revision ID: ce61cbc5b24a
Revises: 37736733007b
Create Date: 2021-12-09 16:42:14.039653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce61cbc5b24a'
down_revision = '37736733007b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('amount', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'prizes', ['name'])
    op.drop_column('prizes', 'qtd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('qtd', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prizes', type_='unique')
    op.drop_column('prizes', 'amount')
    # ### end Alembic commands ###
