"""empty message

Revision ID: cfac3cafdabe
Revises: 4efb2e030944
Create Date: 2021-12-08 11:48:32.408021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfac3cafdabe'
down_revision = '4efb2e030944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
