"""empty message

Revision ID: d09b55c51d81
Revises: 1b177f36fd57
Create Date: 2021-12-08 12:34:38.931473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09b55c51d81'
down_revision = '1b177f36fd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin', 'avatars', ['avatar_id'], ['id'])
    op.drop_column('admin', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'avatar_id')
    # ### end Alembic commands ###
