"""user_model

Revision ID: dda622a0c963
Revises: e46d81ea3d1a
Create Date: 2021-12-07 09:37:39.266948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda622a0c963'
down_revision = 'e46d81ea3d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['user_address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user_address', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user_address', ['user_id'])
    op.create_foreign_key(None, 'user_address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_address', type_='foreignkey')
    op.drop_constraint(None, 'user_address', type_='unique')
    op.drop_column('user_address', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
